### ISSUE TITLE
Problem with Script

### ISSUE THREAD

**Issue by ccolombo71** [inforkgodara/bulk-whatsapp-message-through-python-script#2]
I've installed ... There is the possibility to not disconnect from WhatsApp Web ?

Every type I must scan QRCODE

Can I "memorize" so when I exe script didn't request QRCODE ?

Thanks

**Comment by Jay-Surana** [comment]
It's not possible because u are using a chrome driver which dosent store your data its use for testing softwares. I think my answer is clear enough thanks

**Comment by ccolombo71** [comment]
> It's not possible because u are using a chrome driver which dosent store your data its use for testing softwares. I think my answer is clear enough thanks

Thanks for Your Answer.
I've found a solution and modify your code and it's working.
I scan QRCode only first time and the other time I use the program Chrome open logged in Whatsapp without scan again the QRCode.

Thanks a lot

**Comment by prasad-kanagali** [comment]
> I've found a solution and modify your code and it's working.
> I scan QRCode only first time and the other time I use the program Chrome open logged in Whatsapp without scan again the QRCode.
> 
> Thanks a lot

that's really nice. can you post the modification here so that it will be helpful for the ones looking out for it.

**Comment by eduabreu83** [comment]
> > It's not possible because u are using a chrome driver which dosent store your data its use for testing softwares. I think my answer is clear enough thanks
> 
> Thanks for Your Answer.
> I've found a solution and modify your code and it's working.
> I scan QRCode only first time and the other time I use the program Chrome open logged in Whatsapp without scan again the QRCode.
> 
> Thanks a lot

Can you, share the code?, I need do the same.

**Comment by ccolombo71** [comment]
HI, Here my code 

[Chrome_Comunicazione.py.zip](https://github.com/inforkgodara/python-automated-bulk-whatsapp-messages/files/5858248/Chrome_Comunicazione.py.zip)

Tell me what do you think

**Comment by inforkgodara** [comment]
@ccolombo71 Sorry for the late response. If you want to automate WhatsApp messages via python. You should use Twilio WhatsApp API which will send WhatsApp messages automatically without scanning QR codes else you can use pyautogui python library to accomplish your requirements.

**Comment by inforkgodara** [comment]
Closing the issue.
